version: '3'
services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    build: 
      context: ./backend
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"


volumes:
  dbdata: